kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: react
  namespace: app-dev
  labels:
    app.kubernetes.io/instance: react-app
spec:
  host: react-app-dev.apps.cluster-psp75.psp75.sandbox817.opentlc.com
  to:
    kind: Service
    name: service
    weight: 100
  port:
    targetPort: web
  wildcardPolicy: None
